# Generated by Django 4.2.17 on 2024-12-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressBook',
        ),
    ]
