# Generated by Django 4.2.16 on 2024-12-11 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Track Name')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artist Name')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Track Duration')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='audio/thumbnails/', verbose_name='Track Thumbnail')),
                ('track_file', models.FileField(upload_to='audio/tracks/', verbose_name='Upload Track File')),
                ('track_url', models.URLField(blank=True, null=True, verbose_name='Track URL')),
                ('status', models.IntegerField(choices=[(1, 'Published'), (0, 'Unpublished')], default=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio Track',
                'verbose_name_plural': 'Audio Tracks',
                'db_table': 'audio_tracks',
                'ordering': ['-created_at'],
            },
        ),
    ]
