# Generated by Django 4.2.16 on 2024-12-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_alter_event_created_at_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='myadmin_event',
        ),
    ]
