# Generated by Django 4.2.17 on 2024-12-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_event_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='About Image'),
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
