# Generated by Django 4.2.17 on 2024-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_blogcategory_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Track Duration (seconds)'),
        ),
    ]
