# Generated by Django 4.2.16 on 2024-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification Title')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('target_audience', models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('all', 'All Users')], max_length=20, null=True, verbose_name='Target Audience')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
