# Generated by Django 4.2.17 on 2024-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_alter_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Event Address'),
        ),
    ]
